#!/bin/sh

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/input
DIROUT=$DIRTOOLS/output
MERGE=$DIRTOOLS/py
clear

if [ -d $DIRIN ]; 
then
    echo ""
else
    mkdir $DIRIN $DIROUT
fi

if [ -f $DIRIN/system_file_contexts ]; 
then
	gawk -i inplace 'NR>1' $DIRIN/system_ext_file_contexts
	gawk -i inplace 'NR>1' $DIRIN/product_file_contexts

	python3 $MERGE/system_ext.py $DIRIN/system_ext_file_contexts
	python3 $MERGE/system_ext.py $DIRIN/system_ext_fs_config

	python3 $MERGE/product.py $DIRIN/product_file_contexts
	python3 $MERGE/product.py $DIRIN/product_fs_config


	cat $DIRIN/system_ext_file_contexts >> $DIRIN/system_file_contexts
	cat $DIRIN/system_ext_fs_config >> $DIRIN/system_fs_config

	cat $DIRIN/product_file_contexts >> $DIRIN/system_file_contexts
	cat $DIRIN/product_fs_config >> $DIRIN/system_fs_config


	rm -rf $DIRIN/product*
	rm -rf $DIRIN/system_ext*
	mv $DIRIN/system_file_contexts $DIROUT/
	mv $DIRIN/system_fs_config $DIROUT/

else
	echo "theres no fs context and config in $DIRIN"
	
fi


